name: EpcsView Android CI  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
  
    - name: Set up JDK 17 for Android SDK  
      uses: actions/setup-java@v3  
      with:  
        java-version: '17'  
        distribution: 'temurin'  
  
    - name: Setup Android SDK  
      uses: android-actions/setup-android@v3  
  
    - name: Install Android SDK components  
      run: |  
        sdkmanager "platforms;android-16"  
        sdkmanager "build-tools;22.0.1"  
  
    - name: Set up JDK 8 for Gradle  
      uses: actions/setup-java@v3  
      with:  
        java-version: '8'  
        distribution: 'temurin'  
  
    - name: Create local.properties  
      run: |  
        echo "sdk.dir=$ANDROID_HOME" > local.properties  
  
    - name: Cache Gradle dependencies  
      uses: actions/cache@v3  
      with:  
        path: |  
          ~/.gradle/caches  
          ~/.gradle/wrapper  
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}  
        restore-keys: |  
          ${{ runner.os }}-gradle-  
  
    - name: Make gradlew executable  
      run: chmod +x ./gradlew  
  
    - name: Build with Gradle  
      run: ./gradlew build  
      env:  
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
