name: EpcsView Android CI  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4
  
    - name: Install 32-bit libraries for legacy Android tools  
      run: |  
        sudo dpkg --add-architecture i386  
        sudo apt-get update  
        sudo apt-get install -y libc6:i386 libncurses6:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386  
  
    - name: Set up JDK 17 for Android SDK  
      uses: actions/setup-java@v3  
      with:  
        java-version: '17'  
        distribution: 'temurin'  
  
    - name: Setup Android SDK  
      uses: android-actions/setup-android@v3  
  
    - name: Install Android SDK components  
      run: |  
        sdkmanager "platforms;android-16"  
        sdkmanager "build-tools;22.0.1"  
  
    - name: Set up JDK 8 for Gradle  
      uses: actions/setup-java@v3  
      with:  
        java-version: '8'  
        distribution: 'temurin'  
  
    - name: Fix resource file placement  
      run: |  
        if [ -f "EpcsView/res/layout-land/ic_launcher.png" ]; then  
          mkdir -p EpcsView/res/drawable-land  
          mv EpcsView/res/layout-land/ic_launcher.png EpcsView/res/drawable-land/  
        fi  
  
    - name: Create local.properties  
      run: |  
        echo "sdk.dir=$ANDROID_HOME" > local.properties  
  
    - name: Create gradle.properties for single-threaded build  
      run: |  
        echo "org.gradle.parallel=false" > gradle.properties  
        echo "org.gradle.workers.max=1" >> gradle.properties  
  
    - name: Cache Gradle dependencies  
      uses: actions/cache@v3  
      with:  
        path: |  
          ~/.gradle/caches  
          ~/.gradle/wrapper  
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}  
        restore-keys: |  
          ${{ runner.os }}-gradle-  
  
    - name: Make gradlew executable  
      run: chmod +x ./gradlew  
  
    - name: Build with Gradle  
      run: ./gradlew build  
      env:  
        SLAVE_AAPT_TIMEOUT: 60  
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        
    - name: Upload APK artifacts  
      uses: actions/upload-artifact@v3  
      with:  
        name: apk-files  
        path: |  
          EpcsView/build/outputs/apk/**/*.apk  
        retention-days: 30  
  
    - name: Upload build reports  
      uses: actions/upload-artifact@v3  
      if: always()  
      with:  
        name: build-reports  
        path: |  
          EpcsView/build/reports/  
          EpcsView/build/outputs/lint-results.*  
        retention-days: 7
